apiVersion: apps/v1
kind: Deployment
metadata:
  name: java2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java2
  template:
    metadata:
      labels:
        app: java2
    spec:
      containers:
        - name: java2
          image: vijaykardak/java2:latest
          ports:
            - containerPort: 8080
